TapPaymentIntegration/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using TapPaymentIntegration.Areas.Identity.Data;
using TapPaymentIntegration.Data;
using TapPaymentIntegration.Models.Email;
using TapPaymentIntegration.Models.InvoiceDTO;
using TapPaymentIntegration.Models.PaymentDTO;
using TapPaymentIntegration.Models.UserDTO;
using TapPaymentIntegration.Models.Card;
using ApplicationUser = TapPaymentIntegration.Areas.Identity.Data.ApplicationUser;
using System.Text.Encodings.Web;
using Order = TapPaymentIntegration.Models.InvoiceDTO.Order;
using System.Net.Http.Headers;
using TapPaymentIntegration.Models.Subscription;
using TapPaymentIntegration.Utility;
using TapPaymentIntegration.Models;

namespace TapPaymentIntegration.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private TapPaymentIntegrationContext _context;
        private readonly IUserStore<ApplicationUser> _userStore;
        private IWebHostEnvironment _environment;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        EmailSender _emailSender = new EmailSender();

        public HomeController(IWebHostEnvironment Environment, ILogger<HomeController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, TapPaymentIntegrationContext context, IUserStore<ApplicationUser> userStore)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
            _userStore = userStore;
            _environment = Environment;
        }

        #region Website 
        public IActionResult Index(string id, string userid)
        {
            //var applicationUser = GetCurrentUserAsync().Result;
            //var sub = _context.subscriptions.FirstOrDefault();

            //var bodyemail1 = EmailBodyFill.EmailBodyForPaymentRequest(applicationUser, "jdsjdjdsjgjdsgsdjs");
            //_ = _emailSender.SendEmailAsync("shiraznaseer786@gmail.com", "Tamarran – Payment Request", bodyemail1);

            //var bodyemail2 = EmailBodyFill.EmailBodyForPaymentReceipt(applicationUser);
            //_ = _emailSender.SendEmailAsync("shiraznaseer786@gmail.com", "Tamarran – Payment Receipt", bodyemail2);

            //var bodyemail3 = EmailBodyFill.EmailBodyForAutomaticPaymentConfirmation(sub, applicationUser);
            //_ = _emailSender.SendEmailAsync("shiraznaseer786@gmail.com", "Tamarran - Automatic Payment Confirmation", bodyemail3);

            //var bodyemail4 = EmailBodyFill.EmailBodyForSubscriptionrenewalinTamarranfailed(sub, applicationUser);
            //_ = _emailSender.SendEmailAsync("shiraznaseer786@gmail.com", "Tamarran - Your subscription renewal in Tamarran failed", bodyemail4);


            //var bodyemail5 = EmailBodyFill.EmailBodyForUnsubscriptionSuccessful(applicationUser);
            //_ = _emailSender.SendEmailAsync("shiraznaseer786@gmail.com", "Un-subscription Successful - You're Always Welcome Back!", bodyemail5);


            var subscriptions = _context.subscriptions.Where(x => x.Status).ToList();
            return View(subscriptions);
        }
        public async Task<IActionResult> Subscription(int id, string link, string userid, string invoiceid)
        {
            if (userid != null)
            {
                var applicationUser = _context.Users.Where(x => x.Id == userid).FirstOrDefault();
                await _signInManager.PasswordSignInAsync(applicationUser.UserName.ToString(), applicationUser.Password, true, lockoutOnFailure: true);
            }
            var subscriptions = _context.subscriptions.Where(x => x.Status == true && x.SubscriptionId == id).FirstOrDefault();
            if (subscriptions.VAT == null || subscriptions.VAT == "0")
            {
                subscriptions.VAT = "0";
            }
            ViewBag.Invoiceid = invoiceid;
            return View(subscriptions);
        }
        public async Task<IActionResult> SubscriptionAdmin(int id, string link, string userid, string invoiceid, string After_vat_totalamount)
        {
            if (link != null)
            {
                var applicationUser = _context.Users.Where(x => x.Id == userid).FirstOrDefault();
                await _signInManager.PasswordSignInAsync(applicationUser.UserName.ToString(), applicationUser.Password, true, lockoutOnFailure: true);
            }
            var subscriptions = _context.subscriptions.Where(x => x.Status == true && x.SubscriptionId == id).FirstOrDefault();
            if (subscriptions is null)
            {
                TempData["ErrorMessage"] = Constants.SubscriptionErrorMessage;
                return View();
            }
            var users = _context.Users.Where(x => x.Status == true && x.SubscribeID == id).FirstOrDefault();
            if (subscriptions.VAT == null || subscriptions.VAT == "0")
            {
                subscriptions.VAT = "0";
            }
            ViewBag.Frequency = users.Frequency.ToString();
            ViewBag.Invoiceid = invoiceid;
            ViewBag.After_vat_totalamount = After_vat_totalamount;
            ViewBag.userid = userid;
            ViewBag.PublicKey = users.PublicKey;
            ViewBag.RedirectURL = Constants.RedirectURL;
            return View(subscriptions);
        }
        public async Task<IActionResult> Logout()
        {
            var returnUrl = Url.Action("Index", "Home");
            await _signInManager.SignOutAsync();
            return LocalRedirect(returnUrl);
        }
        #endregion
        #region Tap Charge API
        [HttpPost]
        public async Task<IActionResult> CreateInvoiceMada()
        {
            try
            {
                var Currenturl = Request.Form.Where(x => x.Key == "Currenturl").FirstOrDefault().Value.ToString();
                HttpContext.Session.SetString("Currenturl", Currenturl);
                var Userid = Request.Form.Where(x => x.Key == "Userid").FirstOrDefault().Value.ToString();
                var Invoiceid = Request.Form.Where(x => x.Key == "Invoiceid").FirstOrDefault().Value.ToString();
                ApplicationUser usersinfo = null;
                Invoice invoice = null;
                var Frequency = "";
                var VAT = "";
                if (Userid != "")
                {
                    usersinfo = _context.Users.Where(x => x.Id == Userid).FirstOrDefault();
                    invoice = _context.invoices.Where(x => x.InvoiceId == Convert.ToInt32(Invoiceid)).FirstOrDefault();
                    VAT = invoice.VAT;
                    Frequency = usersinfo.Frequency;
                }
                else
                {
                    Frequency = Request.Form.Where(x => x.Key == "Frequency").FirstOrDefault().Value.ToString();
                    VAT = Request.Form.Where(x => x.Key == "VAT").FirstOrDefault().Value.ToString();
                }
                var TotalPlanfee = Request.Form.Where(x => x.Key == "TotalPlanfee").FirstOrDefault().Value.ToString();
                var SubscriptionId = Request.Form.Where(x => x.Key == "SubscriptionId").FirstOrDefault().Value.ToString();
                var Token = Request.Form.Where(x => x.Key == "Token").FirstOrDefault().Value.ToString();
                if (SubscriptionId != null && Frequency != null)
                {
                    var userinfo = _context.Users.Where(x => x.Id == GetCurrentUserAsync().Result.Id).FirstOrDefault();
                    var subscriptions = _context.subscriptions.Where(x => x.Status == true && x.SubscriptionId == Convert.ToInt32(SubscriptionId)).FirstOrDefault();
                    Random rnd = new Random();
                    var TransNo = "Txn_" + rnd.Next(10000000, 99999999);
                    var OrderNo = "Ord_" + rnd.Next(10000000, 99999999);
                    var amount = TotalPlanfee.ToString();
                    var description = subscriptions.Frequency;
                    Reference reference = new Reference();
                    reference.transaction = TransNo;
                    reference.order = OrderNo;

                    Redirect redirect = new Redirect();
                    redirect.url = Constants.RedirectURL + "/Home/CardVerify";

                    Post post = new Post();
                    post.url = Constants.RedirectURL + "/Home/CardVerifyurl";

                    var countrycode = "";
                    if (userinfo.Country == "Bahrain")
                    {
                        countrycode = "+973";
                    }
                    else if (userinfo.Country == "KSA")
                    {
                        countrycode = "+966";
                    }
                    else if (userinfo.Country == "Kuwait")
                    {
                        countrycode = "+965";
                    }
                    else if (userinfo.Country == "UAE")
                    {
                        countrycode = "+971";
                    }
                    else if (userinfo.Country == "Qatar")
                    {
                        countrycode = "+974";
                    }
                    else if (userinfo.Country == "Oman")
                    {
                        countrycode = "+968";
                    }
                    var currency = subscriptions.Currency;
                    Phone phone = new Phone();
                    phone.number = userinfo.PhoneNumber;
                    phone.country_code = countrycode;

                    Customer customer = new Customer();
                    customer.first_name = userinfo.FullName;

TapPaymentIntegration/Controllers/TapPaymentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using TapPaymentIntegration.Areas.Identity.Data;
using TapPaymentIntegration.Data;
using TapPaymentIntegration.Models;
using TapPaymentIntegration.Models.Card;
using TapPaymentIntegration.Models.UserDTO;

namespace TapPaymentIntegration.Controllers
{
    public class TapPaymentController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private TapPaymentIntegrationContext _context;
        private readonly IUserStore<ApplicationUser> _userStore;
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        public TapPaymentController(ILogger<HomeController> logger, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, TapPaymentIntegrationContext context, IUserStore<ApplicationUser> userStore)
        {
            _logger = logger;
            _signInManager = signInManager;
            _userManager = userManager;
            _context = context;
            _userStore = userStore;
        }
        //Change Card
        public ActionResult ChangeCard()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> ChangeCard(string id)
        {
            var Token = Request.Form.Where(x => x.Key == "Token").FirstOrDefault().Value.ToString();
            if (Token != null)
            {
                //Get Loggedin User Info
                var userinfo = GetCurrentUserAsync().Result;
                var subinfo = _context.subscriptions.Where(x => x.SubscriptionId == userinfo.SubscribeID).FirstOrDefault();
                var countrycode = "";
                if (userinfo.Country == "Bahrain")
                {
                    countrycode = "+973";
                }
                else if (userinfo.Country == "KSA")
                {
                    countrycode = "+966";
                }
                else if (userinfo.Country == "Kuwait")
                {
                    countrycode = "+965";
                }
                else if (userinfo.Country == "UAE")
                {
                    countrycode = "+971";
                }
                else if (userinfo.Country == "Qatar")
                {
                    countrycode = "+974";
                }
                else if (userinfo.Country == "Oman")
                {
                    countrycode = "+968";
                }
                else
                {
                    countrycode = "966";
                }
                var client = new HttpClient();
                var request = new HttpRequestMessage(HttpMethod.Post, "https://api.tap.company/v2/card/verify");
                request.Headers.Add("authorization", "Bearer " + userinfo.SecertKey);
                request.Headers.Add("accept", "application/json");
                var complete_url = Constants.RedirectURL + "TapPayment/ChangeCardResponse";
                var content = new StringContent("{\"currency\":\""+ subinfo.Currency + "\",\"threeDSecure\":true,\"save_card\":true,\"metadata\":{\"udf1\":\"test1\",\"udf2\":\"test2\"},\"customer\":{\"first_name\":\""+userinfo.FullName+"\",\"middle_name\":\"\",\"last_name\":\"\",\"email\":\""+ userinfo.Email+ "\",\"phone\":{\"country_code\":\""+ countrycode + "\",\"number\":\""+userinfo.PhoneNumber+"\"}},\"source\":{\"id\":\""+ Token + "\"},\"redirect\":{\"url\":\""+ complete_url + "\"}}", null, "application/json");
                request.Content = content;
                var response = await client.SendAsync(request);
                var result_erify = await response.Content.ReadAsStringAsync();
                var Deserialized_Deserialized_savecard = JsonConvert.DeserializeObject<VerifyCard>(result_erify);
                HttpContext.Session.SetString("Verify_id", Deserialized_Deserialized_savecard.id);
                return Json(Deserialized_Deserialized_savecard.transaction.url);
            }
            return Json(false);
        }
        public async Task<ActionResult> ChangeCardResponse()
        {
            var userinfo = GetCurrentUserAsync().Result;
            var subinfo = _context.subscriptions.Where(x => x.SubscriptionId == userinfo.SubscribeID).FirstOrDefault();
            var verify_id = HttpContext.Session.GetString("Verify_id");
            var client = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Get, "https://api.tap.company/v2/card/verify/" + verify_id);
            request.Headers.Add("authorization", "Bearer " + userinfo.SecertKey);
            var collection = new List<KeyValuePair<string, string>>();
            collection.Add(new("{}", ""));
            var content = new FormUrlEncodedContent(collection);
            request.Content = content;
            var response = await client.SendAsync(request);
            var result  = await response.Content.ReadAsStringAsync();
            var Deserialized_savecard = JsonConvert.DeserializeObject<RetriveCardResponse>(result);
            //Add Change Card Info
            ChangeCardInfo changeCardInfo = new ChangeCardInfo();
            changeCardInfo.Email = userinfo.Email;
            changeCardInfo.ChangeCardDate = DateTime.UtcNow;
            changeCardInfo.UserName = userinfo.FullName;
            changeCardInfo.SubscriptionName = subinfo.Name;
            changeCardInfo.OldCardName = userinfo.PaymentSource;
            changeCardInfo.NewCardName = Deserialized_savecard.source.payment_method;
            _context.changeCardInfos.Add(changeCardInfo);
            _context.SaveChanges();
            //update user 
            userinfo.Tap_CustomerID = Deserialized_savecard.payment_agreement.contract.customer_id;
            userinfo.Tap_Card_ID = Deserialized_savecard.payment_agreement.contract.id;
            userinfo.Tap_Agreement_ID = Deserialized_savecard.payment_agreement.id;
            userinfo.PaymentSource = Deserialized_savecard.source.payment_method;
            _context.Users.Update(userinfo);
            _context.SaveChanges();
            return View();
        }
        public ActionResult ViewChangeCardInfo()
        {
            var users = _context.changeCardInfos.ToList();
            ViewBag.Userinfo = _context.Users.ToList();
            return View(users);
        }
    }
}

TapPaymentIntegration/Views/Home/AddGymCustomer.cshtml
@model TapPaymentIntegration.Areas.Identity.Data.ApplicationUser
@using Microsoft.Extensions.Configuration
@inject IConfiguration con;
@{
    string googleCaptchaKey = con.GetSection("GoogleCaptcha")["SiteKey"];
    ViewData["Title"] = "Add GYM Customer";
    Layout = "~/Views/Shared/_IdentityLayout.cshtml";
}
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="#" class="h1"><b>Tamarran</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">Sign up to Enter in Tamarran</p>

            @using (Html.BeginForm("AddGymCustomer", "Home", FormMethod.Post))
                {
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="GYMName" placeholder="Enter The GYM Name" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-users"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="FullName" placeholder="Enter The Name" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-users"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" asp-for="UserName" placeholder="Enter The Email" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <select name="Country" class="form-control" id="Country" asp-for="Country" required="required">
                        <option value=" " label="Select a Country" selected="selected">Select a Country</option>
                        <option value="Bahrain" label="Bahrain">Bahrain</option>
                        <option value="KSA" label="KSA">KSA</option>
                        <option value="Kuwait" label="Kuwait">Kuwait</option>
                        <option value="UAE" label="UAE">UAE</option>
                        <option value="Qatar" label="Qatar">Qatar</option>
                        <option value="Oman" label="Oman">Oman</option>
                    </select>
                </div>
                <input type="hidden" value="@ViewBag.SubscriptionList" name="SubscribeID" id="SubscribeID" />
                <div class="input-group mb-3">
                    <input type="text" class="form-control" asp-for="City" placeholder="Enter The City">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-city"></span>
                        </div>
                    </div>
                </div>
                <span style="color:red!important">Enter Phone Number Without Country Code</span>
                <br />
                <div class="input-group mb-3">
                    <input type="number" class="form-control" asp-for="PhoneNumber" placeholder="Enter The Phone Number" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-phone"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input id="password-field" type="password" class="form-control" asp-for="Password" placeholder="Enter The Password" required="required">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-eye toggle-password" toggle="#password-field"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <div class="g-recaptcha" data-sitekey="@googleCaptchaKey"></div>
                </div>
                <input type="hidden" id="recaptchaResponse" name="token" asp-for="recaptchaToken" />
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree" required="required">
                            <label for="agreeTerms">
                                I agree to the <a href="https://www.tamarran.com/En/content/Terms">terms</a>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block" id="SignUp">Sign Up</button>
                    </div>
                    <!-- /.col -->
                </div>
            }
            <p class="mb-1">
                <div asp-validation-summary="All" class="text-danger"></div>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

<partial name="_ValidationScriptsPartial" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(".toggle-password").click(function () {

        $(this).toggleClass("fa-eye fa-eye-slash");
        if ($('#password-field').attr("type") == "password") {
            $('#password-field').attr("type", "text");
        }
        else {
            $('#password-field').attr("type", "password");
        }
    });

    function onClick(e) {
        debugger;
        e.preventDefault();
        grecaptcha.enterprise.ready(async () => {
            document.getElementById('recaptchaResponse').value = await grecaptcha.enterprise.execute('@googleCaptchaKey', { action: 'AddGymCustomer' });
        });
    }
</script>

TapPaymentIntegration/Views/Home/CreateInvoice.cshtml
@model IEnumerable<TapPaymentIntegration.Models.InvoiceDTO.Invoice>
@{
    ViewData["Title"] = "CreateInvoice";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<br />
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header" style="padding: 0.5rem 1.25rem;">
                        <h4 class="text-center mb-0">Invoice List</h4>
                    </div>
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped table-responsive-xl">
                            <thead>
                                <tr style="text-align:center!important">
                                    <th>Invoice Start Date</th>
                                    <th>Invoice End Date</th>
                                    <th>Amount</th>
                                    <th>Status</th>
                                    <th>Subscription Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var user in Model)
                                {
                                    <tr>
                                        <td style="text-align:center!important">
                                            @{
                                                DateTime sdateTime = Convert.ToDateTime(user.InvoiceStartDate);
                                                <span>@sdateTime.ToShortDateString()</span>
                                            }
                                        </td>
                                        <td style="text-align:center!important">
                                            @{
                                                DateTime edateTime = Convert.ToDateTime(user.InvoiceEndDate);
                                                <span>@edateTime.ToShortDateString()</span>
                                            }
                                        </td>
                                        <td style="text-align:center!important">@user.SubscriptionAmount</td>
                                        @if (user.Status == "Payment Captured")
                                        {
                                            <td style="text-align:center!important;color:green!important">@user.Status</td>
                                        }
                                        else
                                        {
                                        <td style="text-align:center!important">@user.Status</td>
                                        }
                                        <td style="text-align:center!important">@user.SubscriptionName</td>
                                        <td style="text-align:center!important">
                                            @if (user.Status != "Payment Captured")
                                            {
                                                <a class="btn btn-primary" href="@Url.Action("Index","TapPayment",new {id = user.InvoiceId, userid = user.UserId})">Pay Invoice</a>
                                                <a class="btn btn-danger" href="@Url.Action("DeleteInvoice","Home",new {id = user.InvoiceId, userid = user.UserId})">Delete Invoice</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,

            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>

TapPaymentIntegration/Views/Home/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@using TapPaymentIntegration.Areas.Identity.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@{
    string displayName = "";
    var UserType = "";
    var user = await UserManager.GetUserAsync(User);
    if (user == null)
    {
        displayName = User.Identity.Name;
        UserType = "Customer";
    }
    else
    {
        UserType = user.UserType;
        displayName = user.FullName;
    }
}
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<br />
@if (UserType != "Customer")
{
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-info">
                        <div class="inner">
                            <h3>@ViewBag.CustomerCount</h3>

                            <p>Customer</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person"></i>
                        </div>
                        <a href="@Url.Action("ViewCustomer","Home")" class="small-box-footer">View Customer<i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3>@ViewBag.InvoiceCount</h3>

                            <p>Received Payment</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-card"></i>
                        </div>
                        <a href="@Url.Action("GetAllCharges","Home")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3>@ViewBag.ChangeCardCount</h3>

                            <p>Change Card</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="@Url.Action("ViewChangeCardInfo","TapPayment")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
                <div class="col-lg-3 col-6">
                    <!-- small box -->
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3>@ViewBag.SubscriptionCount</h3>

                            <p>Subscription Plan</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a href="@Url.Action("Viewsubscription","Home")" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <!-- ./col -->
            </div>
        </div>
    </section>
}